Repository cakephp/authentication, pull requests merged in 2018-04, with the labels that each got.

#192 Added migration info about login action
  docs/Migration-from-the-AuthComponent.md
Labels: documentation

#198 Rename CakeRouterChecker to CakeRouterUrlChecker.
  src/UrlChecker/CakeRouterUrlChecker.php
  tests/TestCase/UrlChecker/CakeRouterUrlCheckerTest.php
Labels: bug

#197 Add support for expanded cookies
  src/Authenticator/CookieAuthenticator.php
  tests/TestCase/Authenticator/CookieAuthenticatorTest.php
Labels: bug

#191 Unauthenticated actions
  docs/Migration-from-the-AuthComponent.md
  docs/Quick-start-and-introduction.md
  src/Controller/Component/AuthenticationComponent.php
  tests/TestCase/Controller/Component/AuthenticationComponentTest.php
Labels: enhancement
