Repository cakephp/authentication, pull requests merged in 2025-04, with the labels that each got.

#699 Fix exception message
  src/Authenticator/AuthenticatorCollection.php
Labels: bug

#708 Allow unauthenticated all
  docs/en/authentication-component.rst
  src/Controller/Component/AuthenticationComponent.php
  tests/TestCase/Controller/Component/AuthenticationComponentTest.php
Labels: enhancement

#714 allow unauthenticatedRedirect as array cake style.
  docs/en/index.rst
  src/AuthenticationService.php
  tests/TestCase/AuthenticationServiceTest.php
Labels: enhancement

#719 Link to impersonation cookbook article
  src/Controller/Component/AuthenticationComponent.php
Labels: enhancement, documentation
